### ISSUE TITLE
value function only running for first in selector

### ISSUE THREAD

**Issue by tylerecouture** [form-o-fill/form-o-fill-chrome-extension#101]
I'm trying to use this code to fill a form in a table:
```
  "fields": [{
    "selector": "input[name*='findme']",
    "value": function($e, data) {
      let $row = $e.closest('tr');
      let name = $row.find('td:nth-child(1)').text();
      return name
    },
  },
```

The function reads the first cell of the row and uses that to fill the selected input element (which is in another cell in that row).

However, for each row, this function returns the same "name" for each field, the one from the first row.  What am I doing wrong here?

EDIT: Ok, this seems like a fake selector?  does it just chose the first element within the query?

```
    "selector": "input",
    "value": function($e, data) {
      return Math.random();
    },
```

returns the same number for every input

**Comment by thenoseman** [comment]
That really sound like a bug. Let me have a look and I'll report back.

**Comment by thenoseman** [comment]
Found the bug 👍  will fix is ASAP.

**Comment by thenoseman** [comment]
Will release 3.8.2 today! Thank you for reporting this nasty bug.
