### ISSUE TITLE
The rule 'value' doesn't work well with <select> using an utf8 character like "Ñ"

### ISSUE THREAD

**Issue by capitangugle** [form-o-fill/form-o-fill-chrome-extension#104]
(I'm using Version 3.8.2)

Hi everybody!,

As I've said, it's a wonderful plugin. I've found a new bug. **It doesn't select the right value ("Español")**, if I use the following rule, because the plugin -right now- only works with non-utf8 characters -not like **"Ñ"**-, at 
least if we are **selecting a value inside a <select> html tag**. 

Check it out at http://www.topocal.com/formreg.php:   

var rules = [{
  "name": "Problem selecting Ñ value inside a <select> html tag",
  "url": "http://www.topocal.com/formreg.php",
  "fields": [
    
    {
    "selector": "#pais",
    "value": "Español"
    },
    
    {
    "selector": "#nombre",
    "value": "Alberto"
    },
    
    {
    "selector": "#email",
    "value": "capitan.gugle@gmail.com"
    },
    
    {
    "selector": "#edad",
    "value": "36"
    },
    
    {
    "selector": "#emailfacebook",
    "value": "capitan.gugle@gmail.com"
    },
    
    {
    "selector": "#profesion",
    "value": "Profesor"
    },
    
    {
    "selector": "#apellidos",
    "value": "Salazar Palomo"
    },
    
    {
    "selector": "#reemail",
    "value": "capitan.gugle@gmail.com"
    },
    
    {
    "selector": "#provincia",
    "value": "Málaga"
    },
    
    {
    "selector": "#sexo",
    "value": "Hombre"
    },

    {
    "selector": "#usuario",
    "value": "capitano1234"
    },
    
    {
    "selector": "#pass",
    "value": "novedoso"
    },    
    
    {
    "selector": "#repass",
    "value": "novedoso"
    },
    
    {
    "selector": "#comentario",
    "value": "Topocal 2018 a por todas!!!"
    },
  
  ]
}
];

However, it work's fine if you select a value like 'Alemania', without the Ñ character -and indeed, maybe another non english characters-:

var rules = [{
  "name": "No problem this way",
  "url": "http://www.topocal.com/formreg.php",
  "fields": [
    
    {
    "selector": "#pais",
    "value": "Alemania"
    },
    
    {
    "selector": "#nombre",
    "value": "Alberto"
    },
    
    {
    "selector": "#email",
    "value": "capitan.gugle@gmail.com"
    },
    
    {
    "selector": "#edad",
    "value": "36"
    },
    
    {
    "selector": "#emailfacebook",
    "value": "capitan.gugle@gmail.com"
    },
    
    {
    "selector": "#profesion",
    "value": "Profesor"
    },
    
    {
    "selector": "#apellidos",
    "value": "Salazar Palomo"
    },
    
    {
    "selector": "#reemail",
    "value": "capitan.gugle@gmail.com"
    },
    
    {
    "selector": "#provincia",
    "value": "Málaga"
    },
    
    {
    "selector": "#sexo",
    "value": "Hombre"
    },

    {
    "selector": "#usuario",
    "value": "capitano1234"
    },
    
    {
    "selector": "#pass",
    "value": "novedoso"
    },    
    
    {
    "selector": "#repass",
    "value": "novedoso"
    },
    
    {
    "selector": "#comentario",
    "value": "Topocal 2018 a por todas!!!"
    },
  
  ]
}
];

**Comment by thenoseman** [comment]
Nice find. I'll validate it if I find time so you'll need to be a little patient :)

**Comment by thenoseman** [comment]
Looks like the page itself is broken and doesn't use the correct UTF-8 encoded `value`for "España":

```
<option value="Espa�a">España</option>
```

As a workaround you can just use that (broken) HTML `"value": "Espa�a"` in your rule.

Works for me even though FoF complains about syntax errors.

Try it :)

**Comment by capitangugle** [comment]
Thank you very much!
