### ISSUE TITLE
Old rules don't work anymore

### ISSUE THREAD

**Issue by pedrotk** [form-o-fill/form-o-fill-chrome-extension#105]
After the update yesterday
All rules with end " * " stop working.

Ex: url: https://www.google.com/*

there is a solution or alternative for this?

**Comment by thenoseman** [comment]
When using `url` you can use a string or a regular expression:

```
url: "https://the.compelte/url?with=some&paramters"
or
url: /https:\/\/google\.com/
```

Be aware that quoting some characters that are "special" in regexp is necessary.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions for some docs on regexps and https://regex101.com/r/brvsYj/1 for your case 

Cheers!
