### ISSUE TITLE
Only absolute urls are working with rules

### ISSUE THREAD

**Issue by nmi-brad** [form-o-fill/form-o-fill-chrome-extension#106]
Hello again,

Have had an issue crop up the last few days with my users where the rules stopped working randomly. I checked everything and ended up coming to the conclusion that if the url was not the absolute url it wouldn't match.

For example, I created a rule for a url like the following: https://subdomain.domain.com/folder/file.php?session=@#$%DDFSDFDS

If I save the rule, it matches flawlessly for just that url. If I remove everything after the file.php, so https://subdomain.domain.com/folder/file.php it no longer matches. I've removed the file.php as well and it still won't match. I confirmed that the URL has nothing special that could have made it look like it was in a different directory.

Any thoughts?

Running Chromium 68.0.3440.75, confirmed not working on the latest Chrome as well.

Thanks,
Brad

**Comment by nmi-brad** [comment]
Issue is still unknown but removing the addon, re-adding and reloading the rules seemed to fix the issue. Still scratching my head but glad its working now.

**Comment by thenoseman** [comment]
In release 3.8.3 I changed the way `"url": "https:/some.url"` works. Actually it was broken and didn't work as described in the help :)

Now if you use `"url" : "a string"` it matches the **whole url only**. Partial matching can be achived using a regular expression, in your case `"url": /subdomain\.domain\.com\/folder\/file\.php/`.

Notice the surrounding `//` and the quoting.

Cheers!
