### ISSUE TITLE
The data in the select field only refreshes when I change the tab

### ISSUE THREAD

**Issue by luis-fonseca** [form-o-fill/form-o-fill-chrome-extension#107]
I needed to create a workflow where it is necessary to fill a select with each state. Afterwards, depending on the selected value, the select with the cities is populated. I created a workflow with two rules, one rule for the first step, and another rule for the second step. The first step is completed and the select field selects the state correctly, but in the second rule, no value in the city field is selected. Only the selection appears when alternating between the browser tabs.

It is worth noting that both the select state field and the select city field are loaded via ajax. The select values of the city field are based on the value of the state field.

Before you run the rule.

![screenshot_2](https://user-images.githubusercontent.com/5729008/46380063-4f618880-c677-11e8-859a-c24bc505172d.png)

After you run the rule and switch between the browser tabs.
![screenshot_4](https://user-images.githubusercontent.com/5729008/46380087-63a58580-c677-11e8-9cac-c70b20fb854d.png)

**Comment by luis-fonseca** [comment]
The rules only work as expected when: they are out of a workflow, I click on the first rule and wait for the execution to complete, I click on the second rule and wait for the execution to finish. In this way, the fields are filled in correctly. Is it possible to create some delay between the tasks in the worflow in order to wait for the data?

**Comment by thenoseman** [comment]
Hi.
Sorry that it took me so long to come back to you.

Sadly currently there is no delay between workflow steps. 

Strangely enough it is possible to delay a *single* rule by using `autorun: <value in miliseconds>` so if I find the time I might even implement that for workflow steps.

Thanks for the idea!

**Comment by luis-fonseca** [comment]
Thanks for the feedback. I was unaware of this feature and tried to use it. It works, but the same problem happened, that is, the field does not update until it alternates between the tabs. I do not know if the framework I use has any influence. I currently use Bootstrap 4 plus jQuery 3.1. *.

**Comment by thenoseman** [comment]
Hey. Would be willing to try out the current development version of this extension?
If so you can find help installing it [here](https://github.com/form-o-fill/form-o-fill-chrome-extension/wiki#how-to-use-the-development-version-of-form-o-fill).

The dev version features a configurable delay *before* every workflow step.

Look for this in the "Workflows" Tab:
<img width="210" alt="fof-delay-wf" src="https://user-images.githubusercontent.com/100459/46570436-7d3f1980-c964-11e8-8633-a82b3a4cd8a5.png">

It would be great if you could try it out and see if it solves your problem.

**Comment by luis-fonseca** [comment]
Greetings.

It took me a while to respond because I had to compile the extension. I did the installation and set it up, but even with the new feature, the problem continues. After starting the workflow, it only ends when alternating between the tabs, which happened in the other case.

PS: In order to compile the extension I needed to install it, npm install -g windows-build-tools.

**Comment by thenoseman** [comment]
Strange. Can you point me to the site you are trying to use FoF on? 
Also the rules you are using would be a good debugging help.

If you don't want to post them publically you can use formofillextension@gmail.com and just send them there.

**Comment by luis-fonseca** [comment]
Thanks for the feedback. I sent a message to the suggested email.

**Comment by thenoseman** [comment]
Received your file and I'll have a look. May take some time because of RealLife(tm) :)

**Comment by YonahKarp** [comment]
Is `delay` available yet in the stable build? It says it is in the "help" section, but I don't see anything like the image you pasted above

![](https://user-images.githubusercontent.com/100459/46570436-7d3f1980-c964-11e8-8633-a82b3a4cd8a5.png)

**Comment by thenoseman** [comment]
Sorry the `delay` didn't make it in so far but *of cause* I forgot to clean up references. Sorry.
