### ISSUE TITLE
fire onChange event after the field is populated

### ISSUE THREAD

**Issue by anking** [form-o-fill/form-o-fill-chrome-extension#108]
if there a way to fire an onChange event after the form field was pupulated so React website can see the actual change?

**Comment by thenoseman** [comment]
Hi.

A `change` event is already being dispatched (see [here](https://github.com/form-o-fill/form-o-fill-chrome-extension/blob/ce842ccfb4d0382a99275e9ba9b10efa6611bfb1/src/js/content/form_filler.js#L107)).

I found that a lot of JS frameworks (react,angular, ember) do more stuff to detect changes and it's very hard to fire the right events.

Anyway to dispatch an event on your own you can use a function for `value`like this:

```
value: function($element, $data) {
  $element.val("my value for the field");
  $element.trigger("some event");
  return null; // This forces Fof to leave the value of the field as it is
}
```
