### ISSUE TITLE
iFrame Fields, e.g. Credit Card Hosted Fields

### ISSUE THREAD

**Issue by ds-clearago** [form-o-fill/form-o-fill-chrome-extension#109]
Hi,

I've not been able to create a rule, that successfully fills hosted payment fields often used for credit card entry with iframes. 
An example for such fields can be found at https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2, but even with a regex url rule, it seems form-o-fill can't find the fields within the iframe although it also satisfies the url rule.

Is there a workaround or a fix in sight?

Best,
Dennis

```
{
  "url": /staging\.clearago\.de\/checkout\/payment-method\/|braintree/,
  "name": "Staging Payment",
  "fields": [{
    "selector": "#id_birth_date",
    "value": "13.12.1991"
  }, {
    "selector": "#id_vat_id",
    "value": "DE123456789"
  }, {
    "selector": "#braintree-hosted-field-cvv",
    "value": "123"
  }, {
    "selector": "#cvv",
    "value": "123"
  }, {
    "selector": "#braintree-hosted-field-credit-card-number",
    "value": "4111111111111111"
  }, {
    "selector": "#credit-card-number",
    "value": "4111111111111111"
  }]
}
```

**Comment by thenoseman** [comment]
Have you tried to use `within: "someselector"`in your rule? 
It is especially made for iframes.
Have a look in the extensions "Help" under "Selecting forms inside iframes".

Hope that works :)

**Comment by thenoseman** [comment]
Did it work?

**Comment by ds-clearago** [comment]
Hey, Thanks completely overlooked that in the help somehow. Tried it now.

This is the rule
```json
{
  "url": "https://staging.clearago.de/checkout/payment-method/",
  "name": "Staging Payment",
  "fields": [{
    "selector": "#id_birth_date",
    "value": "13.12.1991"
  }, {
    "selector": "#id_vat_id",
    "value": "DE123456789"
  }, {
    "within": "#braintree-hosted-field-number",
    "selector": "#credit-card-number",
    "value": "4111111111111111"
  }]
}
```

This is the website's code (excerpt)
```html
...
<div class="form-group mb-20">
	<label for="number">Kartennummer</label>
	<div class="hosted-field form-control" id="number">
		<iframe src="https://assets.braintreegateway.com/..." type="number" name="braintree-hosted-field-number" id="braintree-hosted-field-number">
			<html>
				<head>
					...
				</head>
				<body>
					<form>
						<label for="credit-card-number">Credit Card Number</label>
						<input type="tel" class="number" data-braintree-name="number" name="credit-card-number" id="credit-card-number" maxlength="22">
						</input>
					</form>
				</body>
			</html>
		</iframe>
	</div>
</div>
...
```

It didn't work unfortunately, I guess – as is hinted in the help – because the iframe is on a different domain.

What's odd though, it seems to find the iframe as '"within": "#braintree-hosted-field-numbe"' (missing "r" in the end) yields an error but doing it correctly just yields nothing.

**Comment by thenoseman** [comment]
Yeah, I know that sucks but anyways the browsers nowadays just habe so many security measures in place and usually thats a good thing, right?

That said it sadly limits the things the extension can do.

**Comment by ds-clearago** [comment]
Hm, I thought so. I wonder how it's possible though, that 1Password fills everything flawlessly.
