### ISSUE TITLE
Support Request : If condition=true Then Libs.Halt

### ISSUE THREAD

**Issue by xavierFrance** [form-o-fill/form-o-fill-chrome-extension#110]
Hello,
I am very thankful for this tool, I hope you can offer some help.
I want to create a rule so that "if a text_string is found in the current webpage, then the rule should stop". I need the rule to stop if certain words appear, so that the user can regain control and manually move to the next stage.

This has to be related to the Before function, right ? This is what I (badly) came up with...

var rules = [{
  url: "my_url",
  name: "page 2",
    "before": function(resolve, context) {
    var original_content = window;
    var strFound;
    strFound=original_content.find("my_searched_string");
    if (strfound) Libs.halt;
    resolve(Libs.halt("Custom message to be displayed"));
  },
  fields: [{
    selector: "input[name='finishButton']",
    value: Libs.h.click
  }]
}];

Please help me :)

Thanks a lot,
Xavier

**Comment by thenoseman** [comment]
Hi,
Form-O-Fill will usually run a rule just *once* when a match occurs.

Do you want one rule to be executed over and over again on a single page and then stop once the string is found **or** just once but only if the string is not found?

Cheers,
Frank

**Comment by thenoseman** [comment]
Ok this is what I came up with. Perhaps it can guide you a little :)
```
var rules = [{
  url: /Some-URL-REGEX/,
  name: "Slot available or not?",
  before: function(resolve, context) {
    // Search for <p> with content "no slot is available"
    // Change this to whatever jQuery selector you need!
    // If you use "contains": No quotes inside the ().
    context.findHtml("p:contains(no slot is available)").then(function(html) {
      // See help: "Using the HTML finder in a before/after function"
      // The selector was not found. Happy face ;)
      if (html.length === 0) {
        resolve(Libs.halt("There seems to be an opening!"));
      } else {
        // No slots available found. Sorry :(
        resolve();
      }
    });
  }, 
  fields: [{
    selector: "input[name='finishButton']",
    value: Libs.h.click
  }]
}
];
```

Cheers

**Comment by xavierFrance** [comment]
\o/

Wow, man, you rock. I was worried because the text was not inside a "p" but inside a "form". Yet, it worked great :
(...)
context.findHtml("form:contains(plus de plage horaire libre)").then(function(html) {
(...)

All the best to you !

Cheers
