### ISSUE TITLE
Perform Extraction Again?

### ISSUE THREAD

**Issue by spottedmahn** [form-o-fill/form-o-fill-chrome-extension#114]
Is there a way to perform the extraction again?

Nice tool btw, thanks for creating it! 👏

**Comment by spottedmahn** [comment]
Nvm, found it!  I was right clicking the extension looking for this option... Thoughts about adding it to the extension menu too? 💭

## Right click on the form

![image](https://user-images.githubusercontent.com/14079228/53496818-cfe2b480-3a70-11e9-9b63-952e2f97163c.png)

## Source

Extension help menu:

![image](https://user-images.githubusercontent.com/14079228/53496716-9742db00-3a70-11e9-8d1a-585245d5509b.png)

**Comment by thenoseman** [comment]
Hi!

It's also in the popup when you click the extension in the menu bar thing:
![image](https://user-images.githubusercontent.com/100459/53520896-0e12bf00-3ad7-11e9-9b50-34f9587924cc.png)
Do you mean that or did I miss something?

Recently I saw some extension that also added menu items to the right click menu of the extension icon itself. Must learn how this is done.

**Comment by spottedmahn** [comment]
Hi 👋 -- when I already have a form saved and I want to **re-extract** it, I don't get the popup.  Clicking the extension fills the form.

![image](https://user-images.githubusercontent.com/14079228/53521539-64b3d500-3aa6-11e9-8b4c-ea440fddb1ee.png)
