### ISSUE TITLE
Extracted form has blank fields

### ISSUE THREAD

**Issue by garlandkr** [form-o-fill/form-o-fill-chrome-extension#116]
When using the extract function the fields are empty. Here is what is seen when using import from options:

```javascript
var rules = [{
  "url": "https://www.albiononline2d.com/en/tools/refining-profit-calculator/ore",
  "name": "A rule for https://www.albiononline2d.com/en/tools/refining-profit-calculator/ore",
  "fields": []
}];
```

This is the actual form as seen through Chrome Element Inspect:
```html
<form class="form-inline ng-pristine ng-valid" _lpchecked="1">
    <div class="form-group mx-sm-3" style="background-color: transparent;"><label>Tax</label>&nbsp;<input class="form-control form-control-sm" placeholder="Fee, %" value="25" id="fee"></div>
    <div class="form-group mx-sm-3" style="background-color: transparent;"><label>Return rate</label>&nbsp;<input class="form-control form-control-sm" placeholder="Return rate, %" value="15" id="return-rate"></div>
</form>
```

There are multiple forms on this site and I am trying to fill in all of the text values for these fields:

Craft amount, Tax, Return rate, Master T4, Mastery T5, Mastery T6, Mastery T7, Mastery T8

**Comment by thenoseman** [comment]
Hi,

i learned something today. I previously assumed that the `type`attribute is mandatory on `input` elements.

Well, it isn't and defaults to `type="text"` if not specified.

The extension currently only looks for `input` with a type attribute. 

Nice catch!

**Comment by thenoseman** [comment]
Tested my changes and this looks much better:
```
 {
  "url": "https://www.albiononline2d.com/en/tools/refining-profit-calculator/ore",
  "name": "A rule for https://www.albiononline2d.com/en/tools/refining-profit-calculator/ore",
  "fields": [{
    "selector": "#spec-t4",
    "value": "0"
  }, {
    "selector": "#spec-t5",
    "value": "0"
  }, {
    "selector": "#spec-t6",
    "value": "0"
  }, {
    "selector": "#spec-t7",
    "value": "0"
  }, {
    "selector": "#spec-t8",
    "value": "0"
  }]
}
```

Will push the code soon.

**Comment by thenoseman** [comment]
Version 3.9.1 should be updateable in 60 minutes or so.

**Comment by garlandkr** [comment]
This is great, thank you so much @thenoseman - it works perfectly.
