### ISSUE TITLE
Lost all my rules !

### ISSUE THREAD

**Issue by ligne13** [form-o-fill/form-o-fill-chrome-extension#118]
Hi,

I've lost all the rules I created after trying a Tour (6). Now I only have the Rules for Tour 6.
Is there a way to get my rules back ? I hope so... 🤞

**Comment by thenoseman** [comment]
Sorry :( The isn't.

As it says on every tour page:

```
This is a live tutorial. If you are already using Form-O-Fill please click here to export your rules and workflows before starting this tour.
```

I'm really sorry.
