### ISSUE TITLE
Chrome plugin not working

### ISSUE THREAD

**Issue by agusbce** [form-o-fill/form-o-fill-chrome-extension#120]
Hi! 

The plugin in Chrome has an 404 error to download

![image](https://user-images.githubusercontent.com/61695644/76218461-09f1a500-61f3-11ea-92c7-c9fc27df3db8.png)

**Comment by thenoseman** [comment]
Sorry to say that but google decided to remove Form-O-Fill even after I made the requested changes.

https://github.com/form-o-fill/form-o-fill-chrome-extension#important-notice-about-store-removal
