### ISSUE TITLE
Provide a public email address?

### ISSUE THREAD

**Issue by michael-wavebid** [form-o-fill/form-o-fill-chrome-extension#38]
Frank - love the chrome extension.  I'm interested in discussing customization to fit our needs.  Please contact me.  Sorry to make this an "issue" but I don't know how else to contact you.

**Comment by thenoseman** [comment]
Sorry, I really need to post the email more public :)
You can reach me at formofillextension@gmail.com

**Comment by thenoseman** [comment]
Left the project email in the store description (bottom).

**Comment by michael-wavebid** [comment]
Thanks for getting back to me!  I really did look too for an email address.

I work for a company called Wavebid (https://www.wavebid.com).  We build
tools for auctioneers to make their life easier.  I¹m the CTO, principal
architect, lead developer, etc. etc.  We want to build a chrome extension
that will pull JSON data from our server and use it to populate a form for
instance on craigslist.

    Click on the icon brings up a form where they enter some informationŠ.



When the user clicks ³Find² the code will hit our server and pull back the
matching lot.


This is the part that works.  Now we want to use that lot information to
populate the form on the activeTab and the problem we¹re having is trying to
get the info we pull back in the popup.js sent somewhere that has access to
the activeTab.  It¹s basically a very specific (whittled down) version of
what your extension does where all the data comes from an ajax call.   So
one possibility would be to take what you have and customize it to look and
act like we want.

We¹ve looked extensively at your stuff and tried to write some rules to do
AJAX JSON calls but it doesn¹t work for us, instead of the json data we get
an encoded print of the text of the function.

Would you be open to looking at what we currently have for our chrome
extension and giving us a few pointers?  Maybe we¹re not too far off and
just need a push in the right direction?

Michael

Michael Long | Wavebid | www.wavebid.com <http://www.wavebid.com/>  | 1420 W
26th St. Minneapolis MN 55405 | P: 763-355-3985 x702 | michael@wavebid.com
<mailto:michael@wavebid.com>

From:  Frank Schumacher <notifications@github.com>
Reply-To:  form-o-fill/form-o-fill-chrome-extension
<reply+009f8b3f24a2b181c583d5c89758ef206f8f472cd58e108692cf0000000110c79e3d9
2a169ce033509da@reply.github.com>
Date:  Friday, January 9, 2015 at 7:48 AM
To:  form-o-fill/form-o-fill-chrome-extension
<form-o-fill-chrome-extension@noreply.github.com>
Cc:  Michael Long <michael@wavebid.com>
Subject:  Re: [form-o-fill-chrome-extension] Provide a public email address?
(#38)


Sorry, I really need to post the email more public :)
You can reach me at formofillextension@gmail.com

‹
Reply to this email directly or view it on GitHub
<https://github.com/form-o-fill/form-o-fill-chrome-extension/issues/38#issue
comment-69335951> .
