### ISSUE TITLE
After Function

### ISSUE THREAD

**Issue by SimeonC** [form-o-fill/form-o-fill-chrome-extension#58]
It would be great to have an after option (That had access to jquery ideally). I work in angular and I need to run the following code After all the fields have been filled out to trigger the form validation. If it could do this it would be perfect!

```js
Array.prototype.slice.call(document.querySelectorAll('select,input,textarea')).reduce(function(all, input) {
    var event = document.createEvent('HTMLEvents');
    event.initEvent('change', true, true);
    input.dispatchEvent(event);
    event = document.createEvent('HTMLEvents');
    event.initEvent('input', true, true);
    input.dispatchEvent(event);
    event = document.createEvent('HTMLEvents');
    event.initEvent('keydown', true, true);
    input.dispatchEvent(event);
}, true);
```
Or if I could get jQuery:
```js
$('select,input,textarea').trigger('change').trigger('input').trigger('keydown');
```

**Comment by thenoseman** [comment]
The only problem I see with an "after" hook is that it would not run if the last field definition executes a "Libs.h.click" or changes the page.

But that could easily explained in the help section.

Nice idea. Will queue that up :) Thanks!

**Comment by thenoseman** [comment]
Hi.

I implemented your idea today.

If you can please test the master version (directly from github) and give me feedback if it works for you.

The syntax is:

```javascript
var rules = [{
  name: "teardown",
  url: "something",
  teardownContent: function() {
    // your code. jQuery() is available.
  }, 
  fields: ...
}]
```
See also [this gist](https://gist.github.com/thenoseman/ed8068c4e480d4c59719)

If all goes well this will be in 2.4.1

All the best,
Frank

**Comment by SimeonC** [comment]
Looks like it should work - it runs my code in the right place but my code stopped working so I got some other problems. Thanks!

**Comment by thenoseman** [comment]
Will be in 2.5.0 proper

**Comment by thenoseman** [comment]
2.5.0 is live. please check again with that version.
