### ISSUE TITLE
MutationObserver to watch if forms are added

### ISSUE THREAD

**Issue by hsingh23** [form-o-fill/form-o-fill-chrome-extension#60]
I want to make a form rule for jira - when I click a button a form is created and appended to the dom. On page load this form does not exist so the page shows that no rules match

**Comment by thenoseman** [comment]
Nice idea. Thank you. Actually there already is a NutationObserver inside Form-O-Fill it is just not exposed.
Since observers are very costly (memory wise) I think I will make it optional like so:

```javascript
var rules = [{
  name: "somename",
  observeDom: true // or false
}]
```

What do you think?

**Comment by hsingh23** [comment]
perfect! I saw the mutation observer was in the tutorial, I didn't realize that it was in the code.

**Comment by thenoseman** [comment]
You are using a 
```javascript
content: /something/
```
matcher in your rule right?

I think I will go with polling (every second or so) and thereby remove the possible overhead of the observer.

**Comment by hsingh23** [comment]
I'm using url right now, I could do both url and content. I figure I only
want the overhead of polling in the correct url.

**Comment by thenoseman** [comment]
Ok, will go for this feature next. Stay tuned. Would you be willing to try it out before release?

**Comment by hsingh23** [comment]
Yes, gladly. Is there a beta link?


Peace

Harsh Singh

**Comment by thenoseman** [comment]
Please try it out:

- Download at https://www.dropbox.com/s/emzvqvjp1impbua/form-o-fill-reevaluate-rules.crx?dl=0
- You can install it in parallel with the main extension
- Check out the settings panel: There is a new option called "Re-match rules every two seconds"
  Check that option.

Go back to the jira page.
The extensions icon will turn red signaling that a timer is active.

If you now match a rule on the content that is present when jira has inserted it's <form> you should get a match after ~2 seconds.

Please try it out and tell me if it works for you.

**Comment by hsingh23** [comment]
It works beautifully!

I'd prefer if I could set this option on a per rule basis but I don't mind
it too much as it is.


Peace

Harsh Singh

**Comment by thenoseman** [comment]
Ok, fine. I will include this change in the next version.

Thank you for testing!

I'll keep this issue open until the next version is released

**Comment by hsingh23** [comment]
Thank you soooooo much! I really appreciate your quick responses. Take care
=)


Peace

Harsh Singh

**Comment by thenoseman** [comment]
2.5.0 is live. please check again with that version.

**Comment by hsingh23** [comment]
Woo, it works!


Peace

Harsh Singh

On Wed, Oct 21, 2015 at 10:10 AM, Frank Schumacher <notifications@github.com
