### ISSUE TITLE
Allow remote import

### ISSUE THREAD

**Issue by thenoseman** [form-o-fill/form-o-fill-chrome-extension#66]
Via options:

Import rules from url: [field]

* ~~Must be https (chrome limitation)~~
* replaces complete rule set
* auto updates
* keeps track of version number of file or diffs them (prefer md5 over cotnent and compare this to localstorage)

**Comment by peyn** [comment]
HTTPS - is it really required?

Maybe you could do additional attribute for rule, somethink like a UID (e.g.: com.myCompany.myRule) and then update only the rules contained in the file? This way user could have multiple rules from different sources.

**Comment by thenoseman** [comment]
@peyn Perhaps I'll do that as a second step if the first (replace all) feature works as expected.

Regarding https it seems that adding a CSP policy for "connect-src" makes http work fine. Hopefully :)

**Comment by thenoseman** [comment]
Kindof works in master.

BUGS/TODOS:
- [ ] Color of rules disappear
- [ ] remove shadow storage when settings checkbox is unchecked
- [ ] update shadow onStartup/options open

**Comment by thenoseman** [comment]
Will be in 2.6.0
