### ISSUE TITLE
Looking for support?

### ISSUE THREAD

**Issue by stego-s-aurus** [form-o-fill/form-o-fill-chrome-extension#69]
I Really don't think I'm using this right, please forgive me:

I'm looking for a place or a board or Somewhere where I can get help on writing rules that would trigger the Validation on a Dropdown:

My current rules are as follows:
----------------------------------
var rules = [{
  "url": "(https://ctk.apricot.info/document/edit/form_id/53/parent_id/).+(/id/new)",
  "name": "Food Dist. Record Pickup",
  "autorun": true,
  "fields": [{
    // FCS Service Provider = Coachella Valley Food Distribution -
    "selector": "select[id='field_2173']",
    "value": "Coachella Valley Food Distribution -"
  }, {
    // Location where Service Provided = Mecca Food Project
    "selector": "select[id='field_2175']",
    "value": "Mecca Food Project"
  }, {
    // Select ANY Services Provided = Food assistance
    "selector": "input[id='field_2087_3']",
    "value": true
  }, {
    // Is this a Disaster-related service? = No
    "selector": "input[id='field_2773_1']",
    "value": "No"
  }, {
    // Was NEOP Brochure provided? = No
    "selector": "input[id='field_2645_1']",
    "value": "No"
  },{
    // County where Service Provided = Riverside
    "selector": "input[id='field_2666_0']",
    "value": "Riverside"
  }, {
    // Riverside Food Distribution = Mecca
    "selector": "input[id='field_3072_0']",
    "value": true
  }, {
    // Type of Food Assistance = Food Distribution
    "selector": "input[id='field_728_0']",
    "value": true
  }]
}
];
----------------------------------

As far as the Form Filling, everything works: The two Select fields 2173 and 2175 are Dropdowns.

However, when  I Save the record in my database and come back to look at the record again, the two Dropdowns are Blank!

Looking into the background, I discovered that there is Validation that is going on in the form that is being triggered when I physically "Click" the items: If I just fill them with Form-O-Fill, the Validation never fires; Since the fields are Filled, the database accepts the input without error, and only when I View the record again does the system give me a "These fields must be filled" error.

Is there any way to get Form-O-Fill to Fill the Field AND Simulate a Click on that field at the same time? (The Dropdown by default shows "Please Select", so the Human routine is Click once to drop down the list and then Click again to select the item)

I thank you and pray that the gods of this site have mercy on m soul: Doing charity-related work is quite difficult

**Comment by thenoseman** [comment]
Hi long-extinct-animal ;)

You can use value function to fill the value manually and trigger any event you want.

I'll take Field 2173 (nice name by the way ;)) a an example:
```
{
  // FCS Service Provider = Coachella Valley Food Distribution -
  "selector": "select[id='field_2173']",
  "value": function($element) {
    // $element is the JQuery wrapped <select> 
    $element.val("Coachella Valley Food Distribution -");
    $element.trigger("click"); // Or "change" or whatever event validates the field.
    // return null to stop FoF from filling the field automatically.
   return null;
  }
}
```

Hope that helps!

**Comment by stego-s-aurus** [comment]
Hi!
  It Did fill out the dropdown, but its still isnt firing the Change validation.

This is the screenshot of the page when I physically Click the dropdown:

![image](https://cloud.githubusercontent.com/assets/22183366/18522659/cccb4212-7a65-11e6-8df1-54bb89d10842.png)



and This is what I get after Form-O-Fill runs with the (Thank you very much) Code you supplied:

![image](https://cloud.githubusercontent.com/assets/22183366/18522761/2a5c711c-7a66-11e6-9c30-f01ae5b50198.png)


I can see the Validation is now indeed being done, given that the class "required validation" does indeed show "passed" instead of failed, But something else isn't firing as the "Go To Record" flag that shows when I physically click on it (as seen in the first screenshot) isnt showing up, nor is the <div> that appears below the ...

I tried changing the autorun from true to false to see if it were a timing issue, no luck: When the form loads, there's a moment or so that occurs while those dropdowns are being populated (A Query on the Server runs against another table which populates the list)

I tried changing the autorun from true to false to see if it were a timing issue, no luck...

hmms: I Really do thank you for your assistance on this that you have given so far: This whole project is being done to help convert from an Old (Python?) driven database system over to a Cloud-based database system that the rest of the charity is running on. Being cloud-based means I have no ability to directly change the pages code myself, and so I had to seek out another way to automate some of the minutia for the Volunteers (This code clicks 4 other options on the page For them: There would be 6 options filled in If I can get this to work on the two dropdowns)

**Comment by thenoseman** [comment]
Hi,

Is the "Go To Record" link present in the page but
​ ​
perhaps
​ ​
just hidden via CSS?
If so why don't you just make it visible via $("some-selector").show(); in
the value function?

Strictly speaking this cheating but ... who cares if it works?

If this doesn't work you could try using "Visual Event" (
http://www.sprymedia.co.uk/article/visual+event+2) to display all the bound
event handlers on each item.
Then you know for sure what event to trigger on which element to make "Go
To Record" appear. Give it a shot VE is an awesome Tool for discovery.

Look for "Drag the "Visual Event" link on the right to your bookmark bar:
Visual Event"

--
Frank

2016-09-14 19:39 GMT+02:00 stego-s-aurus <notifications@github.com>:

**Comment by stego-s-aurus** [comment]
Hi there!
  Thank you so much for suggesting Visual Event!

Sadly I don't seem to be any further along in finding out what is in need of being fired in order to allow the record to properly save: This i what I have gotten it to show me so far:

![image](https://cloud.githubusercontent.com/assets/22183366/18724841/b65dd7be-7ff2-11e6-9ff1-e70fec2bf702.png)


Sadly I'm running out of time as this project needs to be running by October 7th: I have been authorized to ask if we can pay you for your time in helping us to get this to function correctly. Do you have access to my email address here? Or is there some other way we can communicate privately?

Thank you in advance!

**Comment by thenoseman** [comment]
Send an email directly to formofillextension-at-gmail.com and we'll get things rolling.
