### ISSUE TITLE
Tutorial modal partially out of window

### ISSUE THREAD

**Issue by LLCampos** [form-o-fill/form-o-fill-chrome-extension#78]
Hi,

Basically, this is happening:

![recored-2016-10-20_121335](https://cloud.githubusercontent.com/assets/12008784/19557748/0d147080-96bf-11e6-865e-c8e8e912da0d.gif)

**Comment by thenoseman** [comment]
Will have a look. Thanks for reporting!

**Comment by LLCampos** [comment]
Yup, solved. ;)
