### ISSUE TITLE
content.css

### ISSUE THREAD

**Issue by LiamDGray** [form-o-fill/form-o-fill-chrome-extension#83]
![form-o-fill content css missing](https://cloud.githubusercontent.com/assets/3453757/21161138/a671e5aa-c144-11e6-81bb-4165328a73a4.png)
content.css doesn’t exist in the repository but is mentioned in manifest.json.

To get Chrome to load the extension (from source in developer mode), I created a blank (empty) content.css, but then, I think that (the emptiness of content.css) may be why the popup windows in options.html are not positioned properly; they are halfway off the screen so that I can’t see them.

Thanks for being patient with this report, which lacks the git checkout tag that you request in README.md. I am writing from work, where I do not have any git client installed.

Form-O-Fill version 3.2.0
(download as a ZIP file on 12 December 2016)

I'd attach logs, but I can't find the logs, perhaps due to the CSS issue?

I am not very fluent in CSS, or I'd fork, write the CSS, and submit a pull request.

Thank you for publishing Form-O-Fill, and for your attention to this issue.

**Comment by thenoseman** [comment]
Hi,

since you load Form-O-Fill in dev mode you must generate the css from the .scss files.
Look in the `src/sass` directory where you'll find the source files.

Go into your checkout directory (where the gulpfile.js is) and do a `gulp sass`. After that all should work fine.

Cheers,
Frank

**Comment by LiamDGray** [comment]
Thanks, Frank. That makes total sense now. Thank you for having patience with my ignorance and haste.

Best,
Liam
