### ISSUE TITLE
Add Math.js library

### ISSUE THREAD

**Issue by kalpitk** [form-o-fill/form-o-fill-chrome-extension#91]
Math.js is a commonly used library in javascript for performing some of the basic mathematical functions

http://cdnjs.cloudflare.com/ajax/libs/mathjs/3.13.3/math.js couldn't be imported as it has got different syntax.

Some modifications need to be done to it and then it can be included in Default Library.

**Comment by thenoseman** [comment]
done in 3.5.0 :)
