### ISSUE TITLE
Extracting option value in optgroup

### ISSUE THREAD

**Issue by umasdai** [form-o-fill/form-o-fill-chrome-extension#93]
Hi, i notice that when extracting a form, it doesnt detect the value that is in optgroup. The id is there in the rule but the value is empty.
Is there any way to extract the value and also fill it to form?

**Comment by umasdai** [comment]
ok, i got it working for setting value which i did like below. But there's still the extracting the value issue if there are any work around. Thanks

"selector": "#visa_collection_center",
"value": function($e, data) {
      $('#visa_collection_center option[value="'+ data.visa_collection_center +'"').attr('selected', 'selected').text();
    }

**Comment by thenoseman** [comment]
Hi, thanks for the report!

I simply forgot optgroups in the extractor :) Well I'll see what I can do after my holiday.

Cheers,
Frank

**Comment by thenoseman** [comment]
Fixed in master, will be in 3.7.0

**Comment by umasdai** [comment]
Thanks, glad to be of little help.

**Comment by thenoseman** [comment]
Finally had time to push 3.7.0 to the store. Try updating the extension in ~60 minutes and <optgroup> should work as expected.
