### ISSUE TITLE
Executing rule doesn't trigger INPUT nor CHANGE events

### ISSUE THREAD

**Issue by thenoseman** [form-o-fill/form-o-fill-chrome-extension#94]
Executing a rule on a form doesn't currently trigger INPUT or CHANGE events.

- Create a setting "Fire events on changed fields", default true
- Fire events for every field type

**Comment by thenoseman** [comment]
@raffomania: Fixed in 3.8.0. Give it a try

**Comment by raffomania** [comment]
The fix works for me, thanks a lot!

**Comment by graemian** [comment]
I suspect this may be broken again in newer versions of React. See https://stackoverflow.com/a/53797269/1420157
