### ISSUE TITLE
Tour 1 seems to be broken with 3.8.0

### ISSUE THREAD

**Issue by thenoseman** [form-o-fill/form-o-fill-chrome-extension#95]

**Comment by markstos** [comment]
The problem isn't just "Tour 1", the whole extraction feature seems to not work using 3.8.0 and Chrome Version 60.0.3112.113 for me. This is in a Chrome profile with no other extensions installed. 

I tried different ways to trigger it, both through the "right click" menu and through the "Extract" option in the menu. I can't get it to work. 

The JavaScript console shows this error after trying the right-click method:

```
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'form' of null
    at chrome-extension://iebbppibdpjldhohknhgjoapijellonp/js/fof_content.js:1:468
```

I hope that's helpful.

**Comment by markstos** [comment]
Wait, now I see the "Tour 1" extraction was also in the output that got pasted into the Rules editor. I wonder why the OP and myself didn't notice this message bar before. Was there and we missed it, or was it actually not there before?  Needs re-testing, I guess.

**Comment by markstos** [comment]
What I'm noticing is happening now is that after I run an Extract and return to the "Rules Editor", there is red band with a message at the top of the screen. When I refresh, the red band flashes and then disappears.

**Comment by markstos** [comment]
It seems that perhaps it appears to fail if the Extension tab is already open, but correctly showed the persistent notification bar when the extension tab was closed when the extraction happened.

**Comment by thenoseman** [comment]
Hi, sorry that I'm so late, reallife(tm) :)

Thanks for debugging this issue so thoroughly. If that's the problem I'll make sure that there is a note on top of every tour prompting the user to close every open FoF option page.

Thank you!

**Comment by thenoseman** [comment]
I really cannot reproduce this error in my setup. Tried everything. Last thing I can think of is some wiered OS issue.
@markstos : Which OS do you use? I'm only on Mac so I can't speak for Windows / Linux users.

**Comment by thenoseman** [comment]
So at least there now is an info message on every tour ...

**Comment by markstos** [comment]
Version 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu
16.04 (64-bit)

**Comment by Phrancis** [comment]
I'm getting a similar issue, although I did not see the above-mentioned JavaScript error.
OS: Windows 10 [Version 10.0.14393]
Chrome version: 62.0.3202.94

When I open Form-O-Fill window and press Extract, nothing happens. I made sure that I was on a page with filled form fields. I restarted Chrome and uninstalled and reinstalled the extension to no avail. The extension icon shows "N/A".

**Comment by thenoseman** [comment]
I'll get a win 10 pc hopefully at the end of this year so I can use that to debug. Sorry this takes so long :(

**Comment by thenoseman** [comment]
Does right clicking and choosing "Form-O-Fill: Save form" work?
