### ISSUE TITLE
Form-o-Fill hanging as soon as I click the red rectangle

### ISSUE THREAD

**Issue by NTTAKR** [form-o-fill/form-o-fill-chrome-extension#98]
Hi!
I would love to use your tool to automate form input during development. 
Testing your tool several times it always hangs as soon as I click the red rectangle. 
No error message, nothing on Debugging Console. After a while Chrome shows that the tab crashed and offers to reload. 

What can I do?

Thanks
  Andreas

**Comment by thenoseman** [comment]
Hi Andreas,

please try to remove other extension you might be using (use a new profile).

If FoF still crashes, please try out the extracted version of FoF (see: https://github.com/form-o-fill/form-o-fill-chrome-extension/wiki#how-to-use-the-development-version-of-form-o-fill)

If it works using the dev-version, please retry the prod version and check if any errors appear *in the background page* by following this [wiki entry](https://github.com/form-o-fill/form-o-fill-chrome-extension/wiki#how-to-use-the-development-version-of-form-o-fill).

Please report back as soon as you have checked, thanks!

**Comment by NTTAKR** [comment]
Hi Frank,

I did all that, but it seems that your function CssSelectorGenerator.prototype.getCombinations struggles as one item it is called with has 43!!! Class entries and looking at the two loops I would say that just was not meant for this number.

[cid:image001.png@01D35504.162D3D10]

Mit freundlichen Grüßen / Best regards,
  Andreas Kroll

NTT-SolutionWare GmbH
Andreas Kroll
Am Hang 1G
40822 Mettmann
Germany

Tel:      +49 (2104) 175 7590
Fax:      +49 (2104) 175 7591
Mobil:   +49 (151) 5288 2476

Sitz der Gesellschaft:          Mettmann                            Bank:                      VR-Bank Mainz
Handelsregisternummer:  HRB 21698                           IBAN:                     DE05 5509 1200 0080 9125 01
Amtsgericht:                        Wuppertal                            BIC:                        GENODE61AZY
Geschäftsführer:                 Andreas Kroll                       Kontoinhaber:     NTT-SolutionWare GmbH

**Comment by thenoseman** [comment]
Thanks for debugging!
CssSelectorGenerator is a third party lib that I use because I'm too lazy to implement it myself :)

Never the less: Can you send me a block of HTML that produces such a large selector?

**Comment by thenoseman** [comment]
Hi,
I think replacing CssSelectorGenerator with https://github.com/Autarc/optimal-select will be the way to go. 
Can you please send me the HTML and target element which produced such a long selector?

**Comment by thenoseman** [comment]
CssSelectorGenerator has been replaced in Form-O-Fill 3.8.1. Please retry!
